###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mariadb
      container_name: mh13-mysql
      working_dir: /application
      volumes:
        - ./docker/data:/var/lib/mysql  
      environment:
        - MYSQL_ROOT_PASSWORD=Fi36101628
        - MYSQL_DATABASE=mh14
        - MYSQL_USER=frankie
        - MYSQL_PASSWORD=Fi36101628
      ports:
        - "8082:3306"
      expose:
        - 3306
        - 8082

    webserver:
      image: nginx:alpine
      container_name: mh13-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./tmp/logs:/var/log/nginx
      ports:
       - "8080:80"
      expose:
        - 3306
        - 8082

    php-fpm:
      build: docker/php-fpm
      container_name: mh13-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

