tinyMCE.addI18n('es.table_dlg',{
general_tab:"General",
advanced_tab:"Avanzado",
general_props:"Propiedades generales",
advanced_props:"Propiedades avanzadas",
rowtype:"Fila en tabla",
title:"Insertar/editar tabla",
width:"Ancho",
height:"Alto",
cols:"Cols",
rows:"Filas",
cellspacing:"Entre celdas",
cellpadding:"Margen interno",
border:"Borde",
align:"Alineación",
align_default:"Por defecto",
align_left:"Izquierda",
align_right:"Derecga",
align_middle:"Centro",
row_title:"Propiedades de fila",
cell_title:"Propiedades de celda",
cell_type:"Tipo de celda",
valign:"Alineación vertical",
align_top:"Arriba",
align_bottom:"Abajo",
bordercolor:"Color de borde",
bgcolor:"Color de fondo",
merge_cells_title:"Fusionar celdas",
id:"Id",
style:"Style",
langdir:"Dirección escritura",
langcode:"Código Idioma",
mime:"Target MIME type",
ltr:"Izquierda a derecha",
rtl:"Derecha a izquierda",
bgimage:"Imagen de fondo",
summary:"Resumen",
td:"Datos",
th:"Cabecera",
cell_cell:"Actualizar celda actual",
cell_row:"Actualizar toda la fila",
cell_all:"Actualizar toda la tabla",
row_row:"Actualizar fila actual",
row_odd:"Actualizar filas impares",
row_even:"Actualizar filas pares",
row_all:"Actualizar todas las filas",
thead:"Cabecera de tabla",
tbody:"Cuerpo de tabla",
tfoot:"Pie de tabla",
scope:"Ámbito",
rowgroup:"Grupo de filas",
colgroup:"Grupo de columnas",
col_limit:"Demasiadas columnas. Máximo: {$cols}.",
row_limit:"Demasiadas filas. Máximo: {$rows}.",
cell_limit:"Demasiadas celdas. Máximo: {$cells}.",
missing_scope:"¿Quieres continuar sin especifica un ámbito para esta cabecera?. Sin ella, puede ser difícil para algunos usuarios discapacitados entender el contenido o los datos mostrados en la tabla.",
caption:"Título de tabla",
frame:"Recuadro",
frame_none:"Ninguno",
frame_groups:"Grupos",
frame_rows:"Filas",
frame_cols:"Columnas",
frame_all:"Todo",
rules:"Reglas",
rules_void:"void",
rules_above:"above",
rules_below:"below",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"box",
rules_border:"border"
});